:PROPERTIES:
:ID:       a296608c-fb22-4730-b166-eddaa1e734b7
:END:
#+title: 2025 Day 5: Cafeteria
#+filetags: :python:

- tags :: [[id:9ca8d2df-3d97-4829-b2b8-db7e08b504ac][aoc2025]]

* Part One

Ranges en ingredienten parsen en dan met een dubbele loop kijken welke spoiled/fresh zijn.

Super handig dat python een else op een loop heb. Dus als een ingredient in 1
van de ranges zit dan break en anders verhoog fresh:


* Part Two

De naive manier hier is om de ranges af te gaan en ze in een set te stoppen. Dan
krijg je wel het antwoord voor het voorbeeld, maar omdat het nogal groot wordt
duurt het voor de echte input te lang.

De invoer bekijkende valt op dat die ranges allemaal door elkaar staan. Het zou
helpen om ze eerst te sorteren. Verder is het zo dat als ik ze eerst uniq maak
er van de 190 nog 172 overblijven dus dat is ook handig om eerst even te doen.

Daarna kunnen de ranges, op volgorde, metelkaar samengevoegd worden. Zodra je
niet meer kan samenvoegen, omdat er geen overlap is, kan voorgaande aantal
bepaald worden en door.

Vergeet niet aan het einde ook nog de range bij het totaat op te tellen!
