:PROPERTIES:
:ID:       e11179d1-3728-44ad-9b5b-8276463ccb49
:END:
#+title: 2024 Day 5: Print Queue
#+filetags: :python:
- tags :: [[id:212a04da-2f2f-42a8-aac3-6cc62a805688][aoc2024]]
- references :: [[id:eec2de7f-8fd0-4e83-90f3-2903bfa6b5ff][2017 Day 1: Inverse Captcha]]


* Part One

Allemaal losse functies gemaakt en die getest.
In eerste instantie wilde ik de tests in een ander bestand doen en dan deze
importeren maar dat bleek nogal lastig want technisch is 05 helemaal geen
geldige variabele naam en dat zou het blijkbaar moeten zijn wil je een module
correct kunnen importeren.

Daarom alle functies naar een apart bestand gehesen en daarnaast de tests gemaakt.
Toen had ik dus 3 bestanden. In latere dagen heb ik ook af en toe tests
geschreven maar dan gewoon in de puzzel oplossing, uiteindelijk heb ik dat bij
deze ook gedaan.

* Part Two

Een comparater gemaakt obv de rules zodat de paginas gesorteert kunnen worden.

De standaard sorted functie van python wil echter een key functie hebben, er is een cmp_to_key in functtools die het voor mij kan ombouwen.
Omdat beide entries nodig zijn voor de vergelijking zie ik geen manier om rechtstreeks een key functie te schrijven.
