:PROPERTIES:
:ID:       df7c3721-b7f9-4910-a76b-260ab63d889b
:END:
#+title: 2024 Day 24: Crossed Wires
#+filetags: :python:
- tags :: [[id:3b4d4e31-7340-4c89-a44d-df55e5d0a3d3][aoc]]
- references :: [[id:c7a78d9c-bf47-41a8-827d-2845e2ad4f0a][2022 Day 23: Unstable Diffusion]]

* Part One
Komt me heel erg bekend voor.
Beetje zoeken. dit lijkt op [[id:b6ff1641-487f-448a-825a-e6c2cf3ce14b][2015 Day 7: Some Assembly Required]]

De operations lijken alleen and or xor te zijn.

Hoe kunnen wires 'no value at all' hebben?
Blijkbaar omdat ze wel in de gates staan maar niet in de input...

Output zit op de z-wires. Dus die van grootstste id naar laagste sorteren en achterklaar plakken.
Dan omzetten van binary naar decimal.

Denk dat ik de gates in een deque zet.
Als ik em niet kan verwerken dan zet ik em terug.

* Part Two

Dus alle x-wires optellen bij alle y-wires.
Zijn alle x en y wel al in de input? -> Ja.

Okay util functie gemaakt om de waarde van de x,y,z wires te berekenen (zelfde als einde van part_one).

ALs je de optelling doet dan zit het al in de buurt:


|        |            dec |                                            bin |
|--------+----------------+------------------------------------------------|
| before | 42049478636360 | 1001100011111001101000001111001011001101001000 |
| after  | 42058069103944 | 1001100100000001101000010001001101010101001000 |
