:PROPERTIES:
:ID:       ad71f962-f149-4ed3-a922-eeff3b40f18d
:END:
#+title: 2019 Day 19: Tractor Beam
#+filetags: :python:
- tags :: [[id:e28a8549-79c6-4060-83a2-a6bcbe0bb09f][aoc2019]] · [[id:8cd1ed8f-6f67-41a6-a8cd-577f8b959eac][intcode]]

* Part One

Had verwacht dat we alle coordinaten wel in 1x kunnen voeren. Maar ik moest de computer voor elk coord opnieuw starten.

* Part Two

Er van uitgaande die straal vanuit 0,0 van links boven naar rechts onder gaat dan zijn er 3 mogelijke afbeeldingen:

1. Zoals in het voorbeeld. De beam verlaat de originele grid zowel aan de onderkant als aan de rechterkant.
2. De beam verlaat de originele grid helemaal aan de onderste kant
3. de beam verlaat de originele grid helemaal aan de rechter kant

Ik zat eerst op de gedachte om de buitenkanten van de beam als vectoren te nemen
en dan te kijken hoe de diagonaal van het vierkant erin te krijgen. Geen idee
hoe dat te doen.

Wat ik ook kan doen, is het programma gebruiken/misbruiken, om de meest linker
zijde van de tractor beam te vinden voor een punt x,y en dan kijken of het
tegenovergestelde punt van het vierkant ook door de beam aangetrokken wordt.
Zodra dit zo is dan bepalen we wat hierin het meest linker hoekje is.

Ik had hier nog wel een of-by-one error.
Als je, van een 100x100 vierkant, het tegenoverliggende punt wilt hebben obv x,y
is het niet x+100,y-100 maar x+99,y-100.

Je moet het zo zien dat je momenteel op het eerste gridpoint van de zijkant staat en je moet naar  het 100ste, dat is 99 stapjes.
