:PROPERTIES:
:ID:       2d9980c9-686e-43bf-95fe-c777c788e4cd
:END:
#+title: 2016 Day 23: Safe Cracking
#+filetags: :python:

- tags :: [[id:7fb73857-09f6-4a05-a470-aec9ac226993][aoc2016]]



* Part One

De uitleg refereerd aan [[id:fe41248e-fb7e-4d5a-8cd2-3df967f323b9][2016 Day 11: Radioisotope Thermoelectric Generators]] en
[[id:8bf34638-57f8-48b2-bd59-ed5424cbbc4a][2016 Day 12: Leonardo's Monorail]]. Omdat het op dit moment [2025-11-08 Sat] een
tijdje geleden is dat ik die heb gemaakt weet ik nu niet of ik die code kan
hergebruiken, of dat er bedoelt word dat het er op lijkt.

Gelukkig staat er bij mijn notities voor dag 12: "Just implement instructions".
Alleen ga ik dat nu wel doen op de manier die ik recent leerde, met [[id:ce560cdc-730c-4861-85db-ebe2c5046fa1][walrus operator]].

Okay deze tgl operator veranderd dus andere operators:

- =inc= -> =dec=
- =dec= -> =inc=
- =jnz= -> =cpy=
- =cpy= -> =jnz=
- =tgl= -> =inc=

Ik zat nog wel ff te kijken waarom ik ooit =ValueError= statements in de code had staan maar dat gaat er over dat die parameters de ene keer een int zijn en de andere keer string. In dat geval moest de waarde van de aangeduide register genomen worden ipv een constante.

Het huidige probleem noemt dat een =tgl= er voor kan zorgen dat een instructie ongeldig wordt.

Als ik het voorbeeld run kan mijn programma niet overweg met =jnz 1 a=, ik moet de conclusie trekken dat in dag 12 het tweede argument nooit een register geweest is.

Voor de rest lijk ik geen invalid instructies tegen te komen want met die 2 aanpassingen (toevoegen van =tgl= en rekening houden dat een jnz als beide params een register kan hebben) heb ik het goede antwoord.

Het voorbeeld zet zelf register a altijd op 3 maar met de echte input moet ik em wel even op 7 zetten.

* Part Two
