:PROPERTIES:
:ID:       08fe7484-1db4-4109-bce1-10c51448fd19
:END:
#+title: 2016 Day 24: Air Duct Spelunking
#+filetags: :python:

- tags :: [[id:7fb73857-09f6-4a05-a470-aec9ac226993][aoc2016]]

* Part One

Dit lijkt een korste pad zoek actie waarbij we niet 1 punt maar meerdere zoeken.
Dus ipv het zoeken stoppen na het vinden van de eind locatie moeten we een =found= lijstje bijhouden en vergelijken met de lijst van =to_visit.=

Meestal hou je, in zoiets, een =visited= list bij en daar moeten alle =to_visit= inzitten.


* Part Two

Mijn gedachte hier is dat we bijhouden welke locaties bezocht zijn en zodra deze hetzelfde is als alle posities in de maze *en* we zijn weer terug bij start dan kunnen we stoppen.

Maar het duurt zeer lang...

Okay ik begreep het probleem verkeerd, ik moest gewoon alle cijfers af en weer terug naar 0. Rare omschrijving ik dacht dat ik de hele maze af moest.

Okay dan nogsteeds dezelfde code als bij deel 1, visited stoppen we niet gelijk de start positie en en we zijn klaar als alle cijfers geweest zijn en we zijn op het laatste punt.
