#+title: 13

* Part One

This is simple multiplication. If we divide the expected departure time by the bus id (retour frequency) we know how many times it can go to and from the airpoirt *before* the expected the departure. If we take the remainder we know how much time it arrives *before* the expected departure. One cycle more and we get the arrival time *after* the expected departure.

so:

minutes before departure = ~departure % bus~
minutes after departure  = ~bus - departure % bus~

* Part Two

No clue, went searching and found mention of the chniese remainder theorem.
+ [[https://en.wikipedia.org/wiki/Chinese_remainder_theorem][Chinese remainder theorem - Wikipedia]]
+ [[https://www.geeksforgeeks.org/introduction-to-chinese-remainder-theorem/][Introduction to Chinese Remainder Theorem - GeeksforGeeks]]

Although the algorithm was quickly implemented. I now need to translate the input to this theorem.
What exactly here are the numbers and remainders that I need to feed the theorem?
