:PROPERTIES:
:ID:       d30168dd-3ac7-4377-be39-32988efd3abc
:END:
#+title: 2020 Day 15: Rambunctious Recitation

- tags :: [[id:5b20c534-bad7-4ba2-bcfe-68c39a6f7f1b][aoc2020]]
* Part One

While searching for a way to get the last index of an element in a list, it seems like that is done by first reversing the list. So I quickly decided to build a reversed list. I can get the actual index by subtracting it from the lenght of the list.

However! when determining the next number the rules are:

#+begin_quote
*how many turns apart* the number is from when it was previously spoken
#+end_quote

Which translates as, "the element index from the end of the list", thus in a reversed list, the index from the start...

* Part Two

Hmm... creating a list of 30m entries takes way too long.

In the hopes that there are a lot of repeating number, I decided to put the last
turn a number was called into a dictionary. This results in the correct answer
in about 7 seconds which is fine with me.

And btw. the resulting dictionary is =175594= entries large, which is a lot smaller than 30m.
